### PR TITLE
Added admin notice if the PHP version requirements are not met

### PR DESCRIPTION
**Pull request by webdeveric**
I updated the plugin entry point to show an admin notice to the user if their server doesn't meet the PHP 5.4+ requirement.
The plugin is also deactivated at this point so that the user is not confused as to why the plugin is active, but not working.

The plugin entry point needs to work with PHP 5.2.4 (WP minimum PHP version) so anonymous functions and namespaces cannot be used.

### CODE REVIEW

**Comment by niallkennedy** [comment]
Thanks for the code. Agree this could be better.

**Comment by coenjacobs** [comment]
I'm probably very biased, but I would be silly if I didn't recommend adding something like https://github.com/WPupdatePHP/wp-update-php to this plugin. This is exactly what I've been meaning to do with the project and I'd be more than happy to have Twitter use this.

It might need a couple tweaks here and there for this specific use case, but I'd be happy to help out.

**Comment by claudiosmweb** [comment]
Don't use `index.php` to that.
This does not follow development best practices for WordPress.
Besides that when updating the plugin, it will be disabled, because changed `twitter.php` to `index.php`.

**Comment by webdeveric** [comment]
@claudiosmweb Good point about the plugin being disabled upon update. I moved the code back to `twitter.php`

I also converted my space indentation to tabs and added `.editorconfig` so my editor will use tabs automatically from now on.

**Comment by niallkennedy** [comment]
I believe the code committed in 27d0251f9d2532af145e54fb1ce823bea3cfd06c addresses the issue with additional capability checks and translated error messages.

**Comment by webdeveric** [comment]
@niallkennedy Agreed. Closing PR.

**Pull request closed without merging**
